export type INCREASE_COUNTER = 'INCREASE_COUNTER';
export const INCREASE_COUNTER: INCREASE_COUNTER = 'INCREASE_COUNTER';

export type DECREASE_COUNTER = 'DECREASE_COUNTER';
export const DECREASE_COUNTER: DECREASE_COUNTER = 'DECREASE_COUNTER';
